import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import profilesRouter from "./profiles";
import followsRouter from "./follows";
import postsRouter from "./posts";
import bootcampsRouter from "./bootcamps";
import channelsRouter from "./channels";
import walletRouter from "./wallet";
import feedRouter from "./feed";
import enrollmentsRouter from "./enrollments";
import seedRouter from "./seed";
import referralsRouter from "./referrals";
import paymentsRouter from "./payments";
import uploadRouter from "./upload";
import bankAccountsRouter from "./bank-accounts";
import notificationsRouter from "./notifications";
import adminRouter from "./admin";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/profiles", profilesRouter);
router.use("/profiles", followsRouter);
router.use("/posts", postsRouter);
router.use("/bootcamps", bootcampsRouter);
router.use("/channels", channelsRouter);
router.use("/wallet", walletRouter);
router.use("/feed", feedRouter);
router.use("/enrollments", enrollmentsRouter);
router.use("/seed", seedRouter);
router.use("/referrals", referralsRouter);
router.use("/payments", paymentsRouter);
router.use("/upload", uploadRouter);
router.use("/bank-accounts", bankAccountsRouter);
router.use("/notifications", notificationsRouter);
router.use("/admin", adminRouter);

export default router;
